-- Initialize database schema and seed data
-- Creates a `users` table and a `"user"` view (so both "user" and users can be queried)

BEGIN;
-- create views here


-- Enums here

CREATE TYPE "required_actions" AS ENUM (
  'client_payment',
  'client_confirmation',
  'employee_confirmation',
  'technician_confirmation'
);

CREATE TYPE "user_role" AS ENUM (
  'manager',
  'client',
  'technician',
  'employee'
);

CREATE TYPE "device_categories" AS ENUM (
  'household_goods',
  'smart_phone',
  'tablet',
  'laptop',
  'pc',
  'printer',
  'other'
);

CREATE TYPE "warranty_type" AS ENUM (
  'basic',
  'extended'
);

CREATE TYPE "repair_status" AS ENUM (
  'pending',
  'checking_warranty',
  'in_progress',
  'completed',
  'cancelled'
);

CREATE TYPE "return_status" AS ENUM (
  'pending',
  'checking_warranty',
  'in_progress',
  'completed',
  'cancelled'
);

CREATE TABLE IF NOT EXISTS "users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar UNIQUE NOT NULL,
  "password" varchar NOT NULL,
  "role" user_role NOT NULL,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE IF NOT EXISTS "clients" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer UNIQUE NOT NULL,
  "full_name" varchar NOT NULL,
  "city" varchar,
  "phone_number" varchar,
  "email" varchar,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE IF NOT EXISTS "technicians" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer UNIQUE NOT NULL,
  "company_name" varchar NOT NULL,
  "city" varchar NOT NULL,
  "capacity" integer DEFAULT 0,
  "max_capacity" integer NOT NULL,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE IF NOT EXISTS "employees" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer UNIQUE NOT NULL,
  "branch_name" varchar NOT NULL,
  "city" varchar,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE IF NOT EXISTS "managers" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer UNIQUE NOT NULL,
  "full_name" varchar NOT NULL,
  "email" varchar,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE IF NOT EXISTS "devices" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "description" text,
  "color" varchar,
  "purchase_cost" double precision,
  "is_damaged" boolean DEFAULT false,
  "image_url" varchar,
  "warranty_id" integer,
  "category" device_categories NOT NULL DEFAULT (other),
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE IF NOT EXISTS "warranties" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "type" warranty_type NOT NULL,
  "starts_at" timestamp NOT NULL,
  "expires_at" timestamp NOT NULL,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE IF NOT EXISTS "repairs" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "status" repair_status NOT NULL DEFAULT 'pending',
  "cost" double precision,
  "device_id" integer NOT NULL,
  "client_id" integer NOT NULL,
  "technician_id" integer NOT NULL,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE IF NOT EXISTS "returns" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "status" return_status NOT NULL DEFAULT 'pending',
  "device_id" integer NOT NULL,
  "client_id" integer NOT NULL,
  "employee_id" integer NOT NULL,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE IF NOT EXISTS "notifications" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "repair_id" integer,
  "return_id" integer,
  "message" varchar NOT NULL,
  "required_actions" required_actions,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE IF NOT EXISTS "kpis" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "metric_name" varchar NOT NULL,
  "metric_value" double precision,
  "period_start" timestamp,
  "period_end" timestamp,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

COMMENT ON COLUMN "users"."username" IS 'Email or username for login';

COMMENT ON COLUMN "technicians"."capacity" IS 'Current workload';

COMMENT ON COLUMN "technicians"."max_capacity" IS 'Maximum capacity';

COMMENT ON COLUMN "devices"."image_url" IS 'URL or path to device image';

COMMENT ON COLUMN "notifications"."repair_id" IS 'Foreign key to repairs, null if this is a return notification';

COMMENT ON COLUMN "notifications"."return_id" IS 'Foreign key to returns, null if this is a repair notification';

COMMENT ON COLUMN "kpis"."metric_name" IS 'e.g., total_repairs, total_returns, average_repair_time';

ALTER TABLE "users" ADD FOREIGN KEY ("id") REFERENCES "clients" ("user_id");

ALTER TABLE "users" ADD FOREIGN KEY ("id") REFERENCES "technicians" ("user_id");

ALTER TABLE "users" ADD FOREIGN KEY ("id") REFERENCES "employees" ("user_id");

ALTER TABLE "users" ADD FOREIGN KEY ("id") REFERENCES "managers" ("user_id");

ALTER TABLE "warranties" ADD FOREIGN KEY ("id") REFERENCES "devices" ("warranty_id");

ALTER TABLE "repairs" ADD FOREIGN KEY ("device_id") REFERENCES "devices" ("id");

ALTER TABLE "repairs" ADD FOREIGN KEY ("client_id") REFERENCES "clients" ("id");

ALTER TABLE "repairs" ADD FOREIGN KEY ("technician_id") REFERENCES "technicians" ("id");

ALTER TABLE "returns" ADD FOREIGN KEY ("device_id") REFERENCES "devices" ("id");

ALTER TABLE "returns" ADD FOREIGN KEY ("client_id") REFERENCES "clients" ("id");

ALTER TABLE "returns" ADD FOREIGN KEY ("employee_id") REFERENCES "employees" ("id");

ALTER TABLE "notifications" ADD FOREIGN KEY ("repair_id") REFERENCES "repairs" ("id");

ALTER TABLE "notifications" ADD FOREIGN KEY ("return_id") REFERENCES "returns" ("id");


-- Seed data here
INSERT INTO users (username, password, role) VALUES
  ('ilias', '123456', 'employee'),
  ('dimitris', '123456', 'employee'),
  ('nikol', '123456', 'technician'),
  ('danis', '123456', 'client'),
  ('themis', '123456', 'client'),
  ('christina', 'redbull', 'client'),
  ('stelios', '123456', 'manager'),
  ('vasiliki', '9dahtila', 'manager')
ON CONFLICT DO NOTHING;

INSERT INTO clients (full_name, email, age) VALUES
  (user_id: 4, 'Danis Litzerinos', 'danis@example.com', '123 Main St, Anytown, USA'),
  (user_id: 5, 'Themis Darelis', 'themis@example.com', '456 Elm St, Anytown, USA'),
  (user_id: 6, 'Christina Tikva', 'christina@example.com', '789 Oak St, Anytown, USA')
ON CONFLICT DO NOTHING;

INSERT INTO technicians (company_name, city, capacity, max_capacity) VALUES
  (user_id: 3, 'Tech Solutions', 'Anytown, USA', 10, 20),
ON CONFLICT DO NOTHING;

INSERT INTO employees (branch_name, city) VALUES
  (user_id: 1, 'Main Branch', 'Anytown, USA'),
  (user_id: 2, 'East Branch', 'Athens, Greece'),
ON CONFLICT DO NOTHING;

INSERT INTO managers (full_name, email) VALUES
  (user_id: 7, 'Stelios Papadopoulos', 'stelios@example.com'),
  (user_id: 8, 'Vasiliki Katsouli', 'vasiliki@example.com')
ON CONFLICT DO NOTHING;

INSERT INTO devices (name, description, color, purchase_cost, is_damaged, image_url, warranty_id, category) VALUES
  ('iPhone 13', 'A new iPhone 13', 'Red', 1000, false, 'https://example.com/iphone13.jpg', 1, 'smart_phone'),
  ('MacBook Pro', 'A new MacBook Pro', 'Silver', 2000, false, 'https://example.com/macbookpro.jpg', 2, 'laptop'),
  ('Dell XPS', 'A new Dell XPS', 'Black', 1500, false, 'https://example.com/dellxps.jpg', 3, 'laptop')
ON CONFLICT DO NOTHING;

INSERT INTO warranties (type, starts_at, expires_at) VALUES
  ('basic', '2025-01-01', '2026-01-01'),
  ('extended', '2025-01-01', '2027-01-01')
  ('basic', '2025-01-01', '2026-01-01'),
ON CONFLICT DO NOTHING;

-- INSERT INTO repairs (status, cost, device_id, client_id, technician_id) VALUES
--   ('pending', 100, 1, 1, 1),
--   ('pending', 200, 2, 2, 2),
--   ('pending', 300, 3, 3, 3)
-- ON CONFLICT DO NOTHING;

-- INSERT INTO returns (status, device_id, client_id, employee_id) VALUES
--   ('pending', 1, 1, 1),
-- COMMIT;
